In [0]:
import numpy as np

## Comparing performance with lists, etc.

In [0]:
N = 100000000

In [0]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 18.3 s, sys: 1.52 s, total: 19.8 s
Wall time: 19.8 s


In [0]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 9.14 s, sys: 3.74 s, total: 12.9 s
Wall time: 12.9 s


In [0]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x, list_)

CPU times: user 2.38 s, sys: 1.43 s, total: 3.81 s
Wall time: 3.82 s


In [0]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

CPU times: user 12.2 s, sys: 1.36 s, total: 13.6 s
Wall time: 13.6 s


In [0]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 2.71 s, sys: 1.34 s, total: 4.05 s
Wall time: 4.04 s


In [0]:
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 349 ms, sys: 5.05 ms, total: 354 ms
Wall time: 365 ms


In [0]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 235 ms, sys: 16 ms, total: 251 ms
Wall time: 252 ms


# Creating np Arrays

In [0]:
arr = np.arange(5)

In [0]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [0]:
arr = np.array([0.0, 2, 4, 6, 8])

In [0]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [0]:
arr

array([0., 2., 4., 6., 8.])

In [0]:
arr.dtype

dtype('float64')

In [0]:
arr.ndim

1

In [0]:
arr.shape

(5,)

In [0]:
arr.size

5

In [0]:
arr.itemsize

8

In [0]:
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6]
])

In [0]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr2d.ndim

2

In [0]:
arr2d.shape

(2, 3)

In [0]:
arr2d.size

6

In [0]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [0]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
arr3d.shape

(2, 2, 3)

In [0]:
arr3d.ndim

3

In [0]:
arr3d.size

12

In [0]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [0]:
1729 * np.ones((2, 3, 4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [0]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [0]:
np.random.randn(2, 3)

array([[ 0.13890333,  0.27855673,  0.21005722],
       [-1.62569229, -0.13162848, -0.95659027]])

In [0]:
np.random.rand(2, 3)

array([[0.3162607 , 0.64561188, 0.15635594],
       [0.8700201 , 0.24331023, 0.6859318 ]])

In [0]:
np.random.rand(10, 1)

array([[0.50711323],
       [0.64183329],
       [0.19184264],
       [0.04014946],
       [0.96683666],
       [0.85560495],
       [0.69896133],
       [0.12290663],
       [0.75425615],
       [0.47505099]])

In [0]:
np.random.randint(0, 100, (2, 3))

array([[34,  0, 49],
       [36, 52, 84]])

In [0]:
np.arange(7, 71, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [0]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [0]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [0]:
str_arr = np.array(['1.4', '2.1', '1.1'])

In [0]:
arr = np.array(str_arr, dtype='float')

In [0]:
arr

array([1.4, 2.1, 1.1])

## indexing

In [0]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [0]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [0]:
arr3d[0, 0, 0]

1

In [0]:
arr3d[1, 0, 2]

9

In [0]:
i = 1
j = 0
k = 2
arr3d[i, j, k]

9

In [0]:
arr3d[1, :, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [0]:
arr3d[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [0]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [0]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [0]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [0]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [0]:
arr_slice = arr3d[:, :, 0:2]

In [0]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [0]:
arr_slice.ndim

3

In [0]:
arr_slice.shape

(2, 2, 2)

In [0]:
arr_slice[0, 0, 1]

2

In [0]:
arr_slice[0, 0, 0] = 1729

In [0]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [0]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [0]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [0]:
arr_slice[0, 0, 0] = 1

In [0]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [0]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [0]:
arr = np.random.randint(0, 10, (5))

In [0]:
arr

array([9, 7, 9, 4, 6])

In [0]:
my_indices = [1, 3, 4]

In [0]:
arr[my_indices]

array([7, 4, 6])

# Numpy Operations

In [0]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [0]:
arr1

array([[0.22962077, 0.51507481, 0.73337689, 0.0732048 ],
       [0.84785699, 0.1344861 , 0.41097148, 0.79916757],
       [0.29367862, 0.72556205, 0.33804899, 0.70370708]])

In [0]:
arr2

array([[0.98809128, 0.08682292, 0.89697772, 0.51651258],
       [0.7306907 , 0.27225471, 0.56516733, 0.84888119],
       [0.02934795, 0.65008809, 0.38822344, 0.74712479]])

In [0]:
arr1 + arr2

array([[1.21771204, 0.60189773, 1.63035461, 0.58971738],
       [1.57854769, 0.40674081, 0.97613881, 1.64804876],
       [0.32302657, 1.37565014, 0.72627243, 1.45083187]])

In [0]:
arr1 - arr2

array([[-0.75847051,  0.4282519 , -0.16360083, -0.44330778],
       [ 0.1171663 , -0.13776861, -0.15419585, -0.04971363],
       [ 0.26433067,  0.07547396, -0.05017445, -0.04341771]])

In [0]:
arr1 * arr2

array([[0.22688627, 0.0447203 , 0.65782273, 0.0378112 ],
       [0.61952122, 0.03661447, 0.23226765, 0.67839832],
       [0.00861886, 0.47167925, 0.13123854, 0.525757  ]])

In [0]:
arr1 / arr2

array([[ 0.23238821,  5.93247539,  0.81760881,  0.14172897],
       [ 1.16035006,  0.49397162,  0.72716779,  0.9414363 ],
       [10.0067855 ,  1.11609804,  0.87075884,  0.94188694]])

In [0]:
np.exp(arr1)

array([[1.2581228 , 1.67376371, 2.08209977, 1.07595087],
       [2.33463834, 1.14394876, 1.50828234, 2.22368909],
       [1.34135275, 2.06589191, 1.4022092 , 2.0212317 ]])

In [0]:
np.log(np.exp(arr1))

array([[0.22962077, 0.51507481, 0.73337689, 0.0732048 ],
       [0.84785699, 0.1344861 , 0.41097148, 0.79916757],
       [0.29367862, 0.72556205, 0.33804899, 0.70370708]])

In [0]:
np.sin(arr1)

array([[0.22760826, 0.49259996, 0.6693822 , 0.07313943],
       [0.74986433, 0.13408107, 0.3995001 , 0.71677588],
       [0.2894753 , 0.66355603, 0.33164714, 0.64704858]])

In [0]:
np.cos(arr1)

array([[0.97375278, 0.87025587, 0.74291821, 0.99732173],
       [0.66159163, 0.99097037, 0.91673315, 0.69730362],
       [0.95718548, 0.74812659, 0.94340351, 0.76244877]])

In [0]:
np.sqrt(arr1)

array([[0.47918761, 0.71768713, 0.85637427, 0.27056385],
       [0.9207915 , 0.36672347, 0.64107057, 0.89396173],
       [0.54192123, 0.8517993 , 0.58141981, 0.8388725 ]])

In [0]:
arr_inv = 1 / arr1

In [0]:
arr_inv

array([[ 4.35500683,  1.94146554,  1.36355538, 13.66030672],
       [ 1.17944418,  7.43571259,  2.43325888,  1.25130203],
       [ 3.40508274,  1.37824187,  2.9581511 ,  1.42104581]])

In [0]:
arr1 = np.zeros((3, 5))

In [0]:
arr_inv = 1/arr1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [0]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [0]:
np.isinf(arr_inv[0,0])

True

In [0]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Broadcasting

In [0]:
arr1 = np.arange(6)

In [0]:
arr1.shape

(6,)

In [0]:
arr1

array([0, 1, 2, 3, 4, 5])

In [0]:
arr1 = arr1.reshape((3, 2))

In [0]:
arr1.shape

(3, 2)

In [0]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
arr2 = np.arange(6).reshape((3, 2))

In [0]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [0]:
arr2[0].reshape((1, 2))

array([[0, 1]])

In [0]:
arr1 + arr2[0].reshape((1, 2)) # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [0]:
arr2[:, 0].reshape((3, 1))

array([[0],
       [2],
       [4]])

In [0]:
arr1 + arr2[:, 0].reshape((3, 1)) # (3, 2) + (3, 1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [0]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
arr1 = np.arange(24).reshape((2, 3, 4))

In [0]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
arr2 = np.ones((1, 4))

In [0]:
arr1 + arr2   # (2, 3, 4) + (1, 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [0]:
arr1 = np.arange(4)

In [0]:
arr2 = np.arange(5)

In [0]:
print(arr1.shape, arr2.shape)

(4,) (5,)


In [0]:
arr1 + arr2

ValueError: ignored

In [0]:
arr1.reshape(4, 1) + arr2  # (4, 1) + (5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [0]:
arr = np.random.rand(3, 3)

In [0]:
arr

array([[0.34623918, 0.14074649, 0.2471035 ],
       [0.82139936, 0.42968499, 0.76271341],
       [0.16353789, 0.85315848, 0.27458889]])

In [0]:
arr.T

array([[0.34623918, 0.82139936, 0.16353789],
       [0.14074649, 0.42968499, 0.85315848],
       [0.2471035 , 0.76271341, 0.27458889]])

# File handling

In [0]:
planets_small = np.loadtxt("planets_small.txt")

ValueError: ignored

In [0]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1)

ValueError: ignored

In [0]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [0]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [0]:
planets_small.shape

(3, 9)

In [0]:
planets = np.loadtxt("planets.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

ValueError: ignored

In [0]:
planets = np.genfromtxt("planets.txt", 
                        skip_header=1, 
                        usecols = [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [0]:
planets.shape

(20, 9)

In [0]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [0]:
planets_new = np.nan_to_num(planets, nan=-1)

In [0]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [0]:
np.savetxt('planets_new.txt', planets_new, 
           delimiter=',')

In [0]:
np.save("planets_new", planets_new)

In [0]:
!ls -lh

total 24K
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [0]:
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)

In [0]:
np.savez("many_arrs", arr1, arr2, arr3)

In [0]:
!ls -lh

total 1.8M
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [0]:
arrs = np.load('many_arrs.npz')

In [0]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [0]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [0]:
arrs['arr_0'].shape

(1000, 10)

In [0]:
np.savez_compressed('many_arrs_compressed', 
                    arr1, arr2, arr3)

In [0]:
!ls -lh

total 3.3M
-rw-r--r-- 1 root root 1.6M Mar 16 14:54 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [0]:
arr1 = np.zeros((10000, 10000))

In [0]:
np.savez("zeros", arr1)

In [0]:
np.savez_compressed("zeros_compressed", arr1)

In [0]:
!ls -lh

total 767M
-rw-r--r-- 1 root root 1.6M Mar 16 14:54 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data
-rw-r--r-- 1 root root 760K Mar 16 14:56 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Mar 16 14:55 zeros.npz


# Stats with NumPy

In [0]:
arr = np.random.rand(10000000,)

In [0]:
np.amin(arr)

2.9102073150211183e-06

In [0]:
np.amax(arr)

0.9999915329470833

In [0]:
np.mean(arr)

0.49835265487727426

In [0]:
np.var(arr)

0.08305664817400735

In [0]:
np.std(arr)

0.28819550338963884

In [0]:
np.median(arr)

0.49774252046580314

In [0]:
np.percentile(arr, 50)

0.49774252046580314

In [0]:
np.percentile(arr, 10)

0.10024188502450737

In [0]:
np.percentile(arr, 90)

0.8985023145814922

In [0]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

CPU times: user 280 ms, sys: 36 ms, total: 316 ms
Wall time: 319 ms


In [0]:
print(iqr)

0.49950783658626163


In [0]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]

CPU times: user 210 ms, sys: 0 ns, total: 210 ms
Wall time: 210 ms


In [0]:
print(quartiles)

[0.24824011 0.74774795]


In [0]:
print(iqr)

0.49950783658626163


In [0]:
(arr - np.mean(arr))/np.std(arr)

array([-1.2076022 , -1.01987303,  1.51760917, ..., -0.47830944,
       -0.33409969,  1.14824894])

In [0]:
np.histogram(arr)

(array([ 999463,  998650, 1000122,  998223, 1000173, 1000919,  998865,
        1000985, 1001600, 1001000]),
 array([8.45622383e-09, 9.99999856e-02, 1.99999963e-01, 2.99999940e-01,
        3.99999917e-01, 4.99999894e-01, 5.99999871e-01, 6.99999849e-01,
        7.99999826e-01, 8.99999803e-01, 9.99999780e-01]))

In [0]:
np.histogram(arr, bins=5)

(array([1998113, 1998345, 2001092, 1999850, 2002600]),
 array([8.45622383e-09, 1.99999963e-01, 3.99999917e-01, 5.99999871e-01,
        7.99999826e-01, 9.99999780e-01]))

In [0]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])

(array([2497818, 2498813, 2500099, 2503270]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [0]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [0]:
np.digitize(arr, bins)

array([1, 1, 4, ..., 2, 2, 4])

In [0]:
arr1 = np.random.randint(0, 10, (10))

In [0]:
arr1

array([2, 8, 8, 2, 6, 0, 8, 2, 7, 9])

In [0]:
bins = [0, 6, 10]

In [0]:
np.digitize(arr1, bins)

array([1, 2, 2, 1, 2, 1, 2, 1, 2, 2])

In [0]:
np.digitize(arr1, bins, right=True)

array([1, 2, 2, 1, 1, 0, 2, 1, 2, 2])

In [0]:
arr1 = np.random.randint(50, 80, 100) # weight

In [0]:
arr2 = np.random.randint(150, 185, 100) # heights

In [0]:
arr3 = np.random.randint(17, 22, 100) # age

In [0]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

In [0]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [0]:
arr2d = np.vstack((arr1, arr2, arr3))

In [0]:
np.amin(arr2d, axis=1)

array([ 50, 150,  17])

In [0]:
np.amax(arr2d, axis=1)

array([ 79, 184,  21])

In [0]:
np.mean(arr2d, axis=1)

array([ 64.48, 167.23,  18.96])

# Checking stats rules with numpy

## Mean subracted array has zero mean

In [0]:
arr = np.random.rand(1000)

In [0]:
mean = np.mean(arr)

In [0]:
arr1 = arr - mean

In [0]:
np.mean(arr1)

-7.105427357601002e-18

## Computing mean with smaller set of values

In [0]:
arr = np.random.rand(1000)

In [0]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

In [0]:
np.cumsum?

In [0]:
means = np.cumsum(arr)/np.arange(1,1001)

In [0]:
means[0:15]

array([0.80334668, 0.47415025, 0.50657624, 0.57224576, 0.6124674 ,
       0.51811314, 0.5048491 , 0.51491554, 0.49235724, 0.54249526,
       0.52085287, 0.48670218, 0.48395448, 0.45357307, 0.48506273])

## Effect of outliers on mean and median

In [0]:
arr = np.random.randint(1, 100, 100)

In [0]:
np.mean(arr)

50.09

In [0]:
np.median(arr)

50.0

In [0]:
arr = np.append(arr, [1000, 2000])

In [0]:
arr.shape

(102,)

In [0]:
np.mean(arr)

78.51960784313725

In [0]:
np.median(arr)

50.5

## Effect of scaling arrays on mean and median

In [0]:
arr = np.random.rand(100)

In [0]:
np.mean(arr)

0.4383130659902099

In [0]:
np.median(arr)

0.3970390836194846

In [0]:
arr1 = 2.5 * arr + 0.65

In [0]:
print(np.mean(2.5 * arr + 0.65), 
      2.5 * np.mean(arr) + 0.65)

1.7457826649755248 1.7457826649755246


In [0]:
print(np.median(2.5 * arr + 0.65), 
      2.5 * np.median(arr) + 0.65)

1.6425977090487114 1.6425977090487116


In [0]:
print(np.var(2.5 * arr + 0.65), 
      2.5*2.5*np.var(arr))

0.4164288169548459 0.4164288169548459


In [0]:
print(np.std(2.5 * arr + 0.65), 
      2.5 * np.std(arr))

0.6453129604733241 0.6453129604733241


In [0]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [0]:
print( np.mean(0.21 * arr1 - 0.75 * arr2), 
      0.21 * np.mean(arr1) - 0.75 * np.mean(arr2))

-0.29677089842238513 -0.29677089842238513
